x = input('digite seu nome: ').strip()
print(x.upper())
print(x.lower())
print(len(x) - x.count(' '))
print(x.find(' '))
separa = x.split()
print(f'seu primeiro nome é {separa[0]} e tem {len(separa[0])} letras')
